# Generated by Django 5.1.4 on 2024-12-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=25, verbose_name='название')),
                ('contents', models.CharField(max_length=200, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото')),
                ('created_at', models.DateField(verbose_name='дата')),
                ('verified', models.BooleanField(default=False, verbose_name='валид')),
                ('count', models.IntegerField(verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
